name: Fetch Articles from Zhihu

on:
  push:
    branches:
      - main # 触发动作的分支
  schedule:
    # 每天UTC时间00:00运行，按需调整
    - cron: '30 7,9 * * *'

jobs:
  fetch_articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create articles directory
        run: mkdir -p articles

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script to fetch articles
        run: python get_articles.py

      - name: Check if 60s_YYYY-MM-DD.json exists
        run: |
          today=$(date -u -d "8 hours" '+%Y-%m-%d')
          cachefile="articles/60s_${today}.json"
          if [ ! -f "$cachefile" ]; then
            echo "Error: $cachefile does not exist."
            exit 1
          fi

      - name: List files in the current directory
        run: ls -la

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          today=$(date -u -d "8 hours" '+%Y-%m-%d')
          cachefile="articles/60s_${today}.json"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $cachefile
          git commit -m "Update $cachefile" || echo "No changes to commit"
          git push
