name: Fetch Articles from Zhihu

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  fetch_articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create articles directory
        run: mkdir -p articles

      - name: Check if today's JSON file exists
        id: check_file
        run: |
          today=$(date -u -d "8 hours" '+%Y-%m-%d')
          cachefile="${GITHUB_WORKSPACE}/articles/60s_${today}.json"
          echo "Checking for file: $cachefile"
          if [ -f "$cachefile" ]; then
            echo "File exists, exiting."
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "File does not exist, will fetch articles."
            echo "file_exists=false" >> $GITHUB_ENV
          fi

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script to fetch articles
        if: env.file_exists == 'false'
        run: python get_articles.py

      - name: Check if 60s_YYYY-MM-DD.json exists
        if: env.file_exists == 'false'
        run: |
          today=$(date -u -d "8 hours" '+%Y-%m-%d')
          cachefile="${GITHUB_WORKSPACE}/articles/60s_${today}.json"
          if [ ! -f "$cachefile" ]; then
            echo "Error: $cachefile does not exist."
            exit 1
          fi

      - name: Commit and push changes
        if: env.file_exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          today=$(date -u -d "8 hours" '+%Y-%m-%d')
          cachefile="${GITHUB_WORKSPACE}/articles/60s_${today}.json"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $cachefile
          git commit -m "Update $cachefile" || echo "No changes to commit"
          git push
